# Gera uma tabuada de um número inteiro inserido pelo usuário.

i = int(input('Digite um número inteiro para gerar uma tabuada: '))
print('=' * 14)
print('{} x {:2} = {}'.format(i, 1, i*1))
print('{} x {:2} = {}'.format(i, 2, i*2))
print('{} x {:2} = {}'.format(i, 3, i*3))
print('{} x {:2} = {}'.format(i, 4, i*4))
print('{} x {:2} = {}'.format(i, 5, i*5))
print('{} x {:2} = {}'.format(i, 6, i*6))
print('{} x {:2} = {}'.format(i, 7, i*7))
print('{} x {:2} = {}'.format(i, 8, i*8))
print('{} x {:2} = {}'.format(i, 9, i*9))
print('{} x {:2} = {}'.format(i, 10, i*10))
print('=' * 14)
